nats:
  config:
    jetstream:
      enabled: true
      fileStore:
        enabled: false
        pvc:
          enabled: false
    mqtt:
      enabled: true
    websocket:
      enabled: true
      tls:
        enabled: false
    cluster:
      enabled: false
  promExporter:
    enabled: true
