apiVersion: v1
kind: Secret
metadata:
  name: keydb-secrets
stringData:
  keydb_masterauth: replica
  users.acl: |
    user admin on ~* >admin &* +@all
    user replica on >replica +@replication
    user default on nopass -@all +ping
    user app on nopass ~* &* +@all -@admin
