apiVersion: v1
kind: Service
metadata:
  name: gitea-runner
  labels:
    app: gitea-runner
spec:
  selector:
    app: gitea-runner
  type: ClusterIP
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea-runner
  labels:
    app: gitea-runner
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitea-runner
  serviceName: gitea-runner
  template:
    metadata:
      labels:
        app: gitea-runner
    spec:
      enableServiceLinks: false
      hostAliases:
      - hostnames:
        - registry.npmjs.org
        - registry-1.docker.io
        - quay.io
        - proxy.golang.org
        ip: 10.43.0.108 # sni-proxy service ip
      #- hostnames:
      #  - gitea.example.com
      #  ip: 10.10.1.1
      containers:
      - name: gitea-runner
        image: quay.io/wener/gitea-runner:0.2.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
          name: web
        env:
        - name: GITEA_INSTANCE_URL
          value: http://gitea
        - name: GITEA_RUNNER_LABELS
          value: ubuntu-latest:docker://wener/node:18,alpine-latest:docker://wener/node:18,alpine-exec:host
        - name: CONFIG_FILE
          value: /etc/gitea/runner/config.yaml
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        envFrom:
        - secretRef:
            name: gitea-runner-env
        volumeMounts:
        - mountPath: /cache
          name: cache
        - mountPath: /root/.pnpm-store
          name: cache
          subPath: .pnpm-store
        - mountPath: /root/.npm
          name: cache
          subPath: .npm
        - mountPath: /root/.m2
          name: cache
          subPath: .m2
        - mountPath: /etc/apk/cache
          name: cache
          subPath: etc/apk/cache
        - mountPath: /data
          name: data
          subPathExpr: $(POD_NAME)
        - mountPath: /root
          name: data
          subPathExpr: $(POD_NAME)/home
        # docker label require docker sock
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /etc/gitea/runner
          name: conf
      volumes:
      - name: conf
        configMap:
          name: gitea-runner-conf
      - name: data
        hostPath:
          path: /data/ns/dev-system/gitea-runner/data
          type: DirectoryOrCreate
      - name: cache
        hostPath:
          path: /data/ns/dev-system/gitea-runner/cache
          type: DirectoryOrCreate
      - name: docker-sock
        hostPath:
          path: /data/ns/dev-system/dind/run/docker.sock
          type: Socket

---

apiVersion: v1
kind: Service
metadata:
  name: gitea-runner
spec:
  selector:
    app: gitea-runner
  ports:
  - protocol: TCP
    port: 80
    targetPort: web
    name: web
