apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-runner-conf
  labels:
    app: gitea-runner
data:
  config.yaml: |
    log:
      level: info
    cache:
      dir: /data/cache
    container:
      workdir_parent: /data/workspace
    runner:
      capacity: 5
    env_file: /etc/gitea/runner/job.env.ini
  job.env.ini: |
    TURBO_API=turborepo-remote-cache
    #TURBO_TEAM
    #TURBO_TOKEN
