apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-runner-conf
  labels:
    app: gitea-runner
data:
  config.yaml: |
    log:
      level: info
    cache:
      enabled: true
      dir: /data/cache
      host: "gitea-runner"
      port: 8088
    container:
      workdir_parent: /data/workspace
