apiVersion: v1
kind: Service
metadata:
  name: gitea-runner
  labels:
    app: gitea-runner
spec:
  selector:
    app: gitea-runner
  type: ClusterIP
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea-runner
  labels:
    app: gitea-runner
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  # need to change token
  replicas: 1
  selector:
    matchLabels:
      app: gitea-runner
  serviceName: gitea-runner
  template:
    metadata:
      labels:
        app: gitea-runner
    spec:
      enableServiceLinks: false
      containers:
      - name: gitea-runner
        image: quay.io/wener/gitea-runner:3.18
        imagePullPolicy: Always
        env:
        - name: GITEA_INSTANCE_URL
          value: http://gitea
        - name: GITEA_RUNNER_LABELS
          value: ubuntu-latest:docker://wener/node:18,alpine-latest:docker://wener/node:18,alpine-exec:host
        - name: CONFIG_FILE
          value: /etc/gitea/runner/config.yaml
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: DOCKER_HOST
          value: unix:///var/run/docker/docker.sock
        envFrom:
        - secretRef:
            name: gitea-runner-env
        volumeMounts:
        - mountPath: /cache
          name: cache
        # sharable cache cross runner
        - mountPath: /root/.pnpm-store
          name: cache
          subPath: .pnpm-store
        - mountPath: /root/.npm
          name: cache
          subPath: .npm
        - mountPath: /root/.m2
          name: cache
          subPath: .m2
        - mountPath: /etc/apk/cache
          name: cache
          subPath: etc/apk/cache
        # primary private data
        - mountPath: /data
          name: data
          subPathExpr: $(POD_NAME)
        # multi runner state
        - mountPath: /root
          name: data
          subPathExpr: $(POD_NAME)/home
        # docker by sock, required for docker label
        - mountPath: /var/run/docker
          name: docker-run
        - mountPath: /etc/gitea/runner
          name: conf
      volumes:
      - name: conf
        configMap:
          name: gitea-runner-conf
      - name: data
        hostPath:
          path: /data/ns/dev-system/gitea-runner/data
          type: DirectoryOrCreate
      - name: cache
        hostPath:
          path: /data/ns/dev-system/gitea-runner/cache
          type: DirectoryOrCreate
      - name: docker-run
        hostPath:
          path: /data/ns/dev-system/dind/run
