{
 "title": "概览",
 "description": "系统全局状态",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "label": "Datasource", "query": "prometheus" },
   { "name": "tenant", "label": "Tenant", "query": ".*" },
   {
    "name": "namespace",
    "label": "Namepsace",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "概览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"probe_success|up\",_tenant=~\"$tenant\"})/count({__name__=~\"probe_success|up\",_tenant=~\"$tenant\"})*100"
    }
   ]
  },
  {
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 13, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(up{job!=\"ping-probe\",_tenant=~\"$tenant\"}, \"instance_ip\", \"$2\", \"instance\", \"(192[.]168[.]|https?://)?([0-9.+]+|.*).*\")",
     "legendFormat": "{{_tenant}}/{{instance_ip}}/{{job}}"
    },
    {
     "expr": "label_replace(probe_success{_tenant=~\"$tenant\"}, \"instance_ip\", \"$2\", \"instance\", \"(192[.]168[.]|https?://)?([0-9.+]+|.*).*\")",
     "legendFormat": "{{_tenant}}/{{instance_ip}}/{{job}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"probe_success|up\",_tenant=~\"$tenant\"})",
     "legendFormat": "监控目标"
    }
   ]
  },
  {
   "title": "面板",
   "type": "dashlist",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "收藏面板",
   "type": "dashlist",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Linux",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Linux Nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "node_uname_info{_tenant=~\"$tenant\"} - 0"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{_tenant=~\"$tenant\"})by(instance)"
    },
    {
     "expr": "node_memory_MemTotal_bytes{_tenant=~\"$tenant\"} - 0"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\",_tenant=~\"$tenant\"}) by (instance)"
    },
    {
     "expr": "node_load5{_tenant=~\"$tenant\"}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",_tenant=~\"$tenant\"}[$__rate_interval])) by (instance)) * 100"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{_tenant=~\"$tenant\"} / (node_memory_MemTotal_bytes{_tenant=~\"$tenant\"})))* 100"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs|zfs\",_tenant=~\"$tenant\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs|zfs\",_tenant=~\"$tenant\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs|zfs\",_tenant=\"$tenant\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs|zfs\",_tenant=~\"$tenant\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs|zfs\",_tenant=~\"$tenant\"})))by(instance)"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{_tenant=~\"$tenant\"}[$__rate_interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{_tenant=~\"$tenant\"}[$__rate_interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{_tenant=~\"$tenant\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{_tenant=~\"$tenant\"} - 0",
     "legendFormat": "TCP Time Wait"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{_tenant=~\"$tenant\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{_tenant=~\"$tenant\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Pod",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Windows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Windows节点",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_cs_hostname{_tenant=~\"$tenant\"}-0"
    },
    {
     "expr": "time() - windows_system_system_up_time{_tenant=~\"$tenant\"}"
    },
    {
     "expr": "windows_cs_logical_processors{_tenant=~\"$tenant\"} - 0"
    },
    {
     "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{_tenant=~\"$tenant\"}) * 1000 * 1000"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{_tenant=~\"$tenant\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{_tenant=~\"$tenant\"} - 0"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{_tenant=~\"$tenant\"} / windows_cs_physical_memory_bytes{_tenant=~\"$tenant\"}",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "1 - (windows_logical_disk_free_bytes{_tenant=~\"$tenant\",volume=~\"C:\"}/windows_logical_disk_size_bytes{_tenant=~\"$tenant\",volume=~\"C:\"})"
    },
    {
     "expr": "max by (instance) (1-windows_logical_disk_free_bytes{_tenant=~\"$tenant\"}/windows_logical_disk_size_bytes{_tenant=~\"$tenant\"})"
    },
    {
     "expr": "windows_os_processes{_tenant=~\"$tenant\"}"
    },
    {
     "expr": "sum by (instance) (windows_service_state{_tenant=~\"$tenant\",state=~\"running\"})"
    }
   ]
  }
 ]
}