apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: buypass
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://api.buypass.com/acme/directory
    privateKeySecretRef:
      name: buypass-account
    solvers:
    - http01:
        ingress: { }
