apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: buypass-staging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://api.test4.buypass.no/acme-v02/directory
    privateKeySecretRef:
      name: buypass-staging-account
    solvers:
    - http01:
        ingress: { }
