apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/argocd-instance: argocd
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  application.resourceTrackingMethod: annotation
  ga.trackingid: ''

# prefer secret
# repositories: |
#   - name: kube-stub-cluster
#     url: https://github.com/wenerme/kube-stub-cluster.git

# username+password
#    - passwordSecret:
#        key: password
#        name: repo-wenerme-kube-stub-cluster
#      usernameSecret:
#        key: username
#        name: repo-wenerme-kube-stub-cluster
#      type: git
#      name: kube-stub-cluster
#      url: https://github.com/wenerme/kube-stub-cluster.git
#
# internal git+ssh
#    - insecure: true
#      insecureIgnoreHostKey: true
#      name: cluster-deploy
#      sshPrivateKeySecret:
#        key: sshPrivateKey
#        name: repo-cluster-cluster-deploy
#      type: git
#      url: git@gitea-ssh.gitea:cluster/cluster-deploy
