apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-kubernetes-secrets
  labels:
    app: drone-kubernetes-secrets
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  template:
    metadata:
      name: drone-kubernetes-secrets
      labels:
        app: drone-kubernetes-secrets
    spec:
      containers:
      - name: drone-kubernetes-secrets
        image: drone/kubernetes-secrets:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: drone-kubernetes-secrets-env
        ports:
        - containerPort: 3000
          name: web
      restartPolicy: Always
  selector:
    matchLabels:
      app: drone-kubernetes-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: drone-kubernetes-secrets
  labels:
    app: drone-kubernetes-secrets
spec:
  selector:
    app: drone-kubernetes-secrets
  ports:
  - port: 80
    targetPort: web
    name: web

