apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
  labels:
    app: drone
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  template:
    metadata:
      name: drone
      labels:
        app: drone
    spec:
      containers:
      - name: drone
        image: drone/drone:2.16.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        envFrom:
        - secretRef:
            name: drone-env
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        hostPath:
          path: /data/ns/dev-system/drone/data
      restartPolicy: Always
  selector:
    matchLabels:
      app: drone

---

apiVersion: v1
kind: Service
metadata:
  name: drone
spec:
  selector:
    app: drone
  ports:
  - port: 80
    targetPort: web
    name: web
