apiVersion: v1
kind: Secret
metadata:
  name: drone-docker-runner-env
  labels:
    app: drone-docker-runner
stringData:
  # https://docs.drone.io/runner/docker/configuration/reference/
  DRONE_RPC_SECRET: $(DRONE_RPC_SECRET)
  DRONE_RPC_PROTO: http
  DRONE_RPC_HOST: drone
  DRONE_RUNNER_NAME: docker-runner
  DRONE_RUNNER_CAPACITY: '10'
  DRONE_DEBUG: 'true'
  DRONE_TRACE: 'true'
  DRONE_NETRC_CLONE_ONLY: 'true'
  DRONE_RUNNER_VOLUMES: /var/run/docker.sock:/var/run/docker.sock

#  DRONE_UI_USERNAME: root
#  DRONE_UI_PASSWORD: root
#  # 实在不知道怎么解决 授权问题
#  DRONE_NETRC_FILE: |
#    machine code.example.com
#    login gitea
#    password gitea

#  DRONE_SECRET_PLUGIN_ENDPOINT: http://drone-kubernetes-secrets
#  DRONE_SECRET_PLUGIN_TOKEN: $(DRONE_SECRET_PLUGIN_TOKEN)
#  DRONE_GIT_PASSWORD: $(DRONE_GIT_PASSWORD)
#  DRONE_GIT_ALWAYS_AUTH: 'true'
#  DRONE_GIT_USERNAME: gitea
