apiVersion: v1
kind: Secret
metadata:
  name: drone-env
  labels:
    app: drone
stringData:
  DRONE_GITEA_CLIENT_ID: $(DRONE_GITEA_CLIENT_ID)
  DRONE_GITEA_CLIENT_SECRET: $(DRONE_GITEA_CLIENT_SECRET)
  DRONE_GITEA_SERVER: https://code.example.com
  DRONE_SERVER_HOST: drone.example.com
  DRONE_SERVER_PROTO: https
  DRONE_RPC_SECRET: $(DRONE_RPC_SECRET)
  DRONE_GIT_ALWAYS_AUTH: 'true'
#  DRONE_GIT_USERNAME: gitea
#  DRONE_GIT_PASSWORD: gitea
#  DRONE_USER_CREATE: gitea:wener,admin:true
