haproxytech-ingress:
  controller:
    # 按需调整
    ingressClassResource:
      name: haproxy
      default: false
    extraArgs:
    # default to ingress
    # - --default-backend-service=ingress-nginx/ingress-nginx-controller
    # Deployment can rolling update - DaemonSet can reduce routing
    kind: DaemonSet
    replicaCount: 1
    daemonset:
      useHostPort: true
      hostPorts:
        http: 80
        https: 443
        stat: 1024

    extraEnvs:
    - name: TZ
      value: Asia/Shanghai
    config: {}
      # chain proxy
      # proxy-protocol: 192.168.1.1

  # k8s.gcr.io/defaultbackend-amd64
  defaultBackend:
    enabled: false
    image:
      repository: registry.cn-hongkong.aliyuncs.com/cmi/defaultbackend-amd64
