apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # CHANGEMD depends
    namespace: oauth2-proxy
  project: default
  source:
    path: oauth2-proxy
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
