apiVersion: v1
kind: Secret
metadata:
  name: grafana-env
stringData:
  GF_SECURITY_ADMIN_USER: ""
  GF_SECURITY_ADMIN_PASSWORD: ""
  GF_SECURITY_DISABLE_GRAVATAR: "true"
  GF_ANALYTICS_REPORTING_ENABLED: "false"
  GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
  GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: "false"
  GF_USERS_DEFAULT_LANGUAGE: "zh-Hans"
  # GF_USERS_AUTO_ASSIGN_ORG_ID: "2"
  GF_DATABASE_URL: ""
