grafana:
  ingress:
    enabled: true
    hosts:
    - monitor.example.com
  envFromSecret: grafana-env
  admin:
    existingSecret: grafana-env
    userKey: GF_SECURITY_ADMIN_USER
    passwordKey: GF_SECURITY_ADMIN_PASSWORD
  plugins:
  - grafana-clock-panel
  - grafana-polystat-panel
  podAnnotations:
    reloader.stakater.com/auto: 'true'
  grafana.ini:
    server:
    # root_url: https://monitor.example.com
  env:
  # https_proxy: 'http://proxy.dev-system:1080'
