apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applicationset
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
  source:
    path: argocd-applicationset
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
