apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-agent-docker-env
stringData:
  WOODPECKER_HOSTNAME: woodpecker-agent-docker-1
  WOODPECKER_SERVER: woodpecker:9000
  WOODPECKER_AGENT_SECRET: ${WOODPECKER_AGENT_SECRET}
  WOODPECKER_MAX_PROCS: '10'
  WOODPECKER_LOG_LEVEL: trace
  WOODPECKER_DEBUG_PRETTY: 'true'
