apiVersion: apps/v1
kind: Deployment
metadata:
  name: woodpecker
  labels:
    app: woodpecker
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  template:
    metadata:
      name: woodpecker
      labels:
        app: woodpecker
    spec:
      containers:
      - name: woodpecker
        #image: woodpeckerci/woodpecker-server:v0.15.7-alpine
        image: woodpeckerci/woodpecker-server:next-3a475ce210-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        envFrom:
        - secretRef:
            name: woodpecker-env
        ports:
        - containerPort: 8000
          name: web
        - containerPort: 9000
          name: grpc
        startupProbe:
          httpGet:
            port: web
            path: /version
        volumeMounts:
        - mountPath: /var/lib/woodpecker/
          name: data
          # woodpecker.sqlite
      volumes:
      - name: data
        hostPath:
          path: /data/ns/dev-system/woodpecker/data
      restartPolicy: Always
  selector:
    matchLabels:
      app: woodpecker

---

apiVersion: v1
kind: Service
metadata:
  name: woodpecker
spec:
  selector:
    app: woodpecker
  ports:
  - port: 80
    targetPort: web
    name: web
  - port: 9000
    targetPort: grpc
    name: grpc

