apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-env
stringData:
  WOODPECKER_LOG_LEVEL: trace
  WOODPECKER_OPEN: 'false'
  WOODPECKER_HOST: ${WOODPECKER_HOST}
  WOODPECKER_ADMIN: gitea
  WOODPECKER_PROMETHEUS_AUTH_TOKEN: ${WOODPECKER_PROMETHEUS_AUTH_TOKEN}
  WOODPECKER_GITEA: 'true'
  WOODPECKER_GITEA_URL: ${WOODPECKER_GITEA_URL}
  WOODPECKER_GITEA_CLIENT: ${WOODPECKER_GITEA_CLIENT}
  WOODPECKER_GITEA_SECRET: ${WOODPECKER_GITEA_SECRET}
  WOODPECKER_AGENT_SECRET: ${WOODPECKER_AGENT_SECRET}
  WOODPECKER_ESCALATE: plugins/docker,plugins/gcr,plugins/ecr,woodpeckerci/plugin-docker,woodpeckerci/plugin-docker-buildx,wener/docker
