apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-agent-local-env
stringData:
  WOODPECKER_BACKEND: local
  WOODPECKER_FILTER_LABELS: runner=exec
  WOODPECKER_HOSTNAME: woodpecker-agent-local-1
  WOODPECKER_SERVER: woodpecker:9000
  WOODPECKER_AGENT_SECRET: ${WOODPECKER_AGENT_SECRET}
  WOODPECKER_MAX_PROCS: '10'
  WOODPECKER_LOG_LEVEL: trace
  WOODPECKER_DEBUG_PRETTY: 'true'
