apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-node-port
  labels:
    app.kubernetes.io/name: kube-prometheus
spec:
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prometheus-prometheus
  type: NodePort
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30909
