apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator-ui
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: postgres-operator
  source:
    path: postgres-operator-ui
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
