apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crds.yaml
- deployment.yaml
- rbac.yaml
namespace: monitoring-system
images:
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: registry.cn-hongkong.aliyuncs.com/cmi/kubebuilder_kube-rbac-proxy
- name: quay.io/grafana-operator/grafana-operator
  newName: registry.cn-hongkong.aliyuncs.com/cmi/grafana-operator_grafana-operator
