apiVersion: v1
kind: Service
metadata:
  name: dockercr
spec:
  ports:
  - port: 5000
    name: registry
  - port: 5001
    name: debug
  clusterIP: None

---

apiVersion: v1
kind: Endpoints
metadata:
  name: dockercr
subsets:
# forward external dockercr mirror
- addresses:
  - ip: 192.168.1.1
  ports:
  - port: 5000
    name: registry
  - port: 5001
    name: debug
