apiVersion: apps/v1
kind: Deployment
metadata:
  name: quaycr
  labels:
    app: quaycr
spec:
  replicas: 1
  template:
    metadata:
      name: quaycr
      labels:
        app: quaycr
    spec:
      containers:
      - name: registry
        image: registry:2.8.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: registry
        - containerPort: 5001
          name: debug
        startupProbe:
          httpGet:
            port: registry
            path: /v2/
        env:
        - name: https_proxy
          value: clash:7890
        - name: REGISTRY_PROXY_REMOTEURL
          value: https://quay.io
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_HTTP_HOST
          value: https://quaycr.example.com
        - name: REGISTRY_HTTP_DEBUG_ADDR
          value: :5001
        - name: REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED
          value: "true"
        volumeMounts:
        - mountPath: /var/lib/registry
          name: data
      volumes:
      - name: data
        hostPath:
          path: /data/ns/dev-system/quaycr/data
      restartPolicy: Always
  selector:
    matchLabels:
      app: quaycr

---

apiVersion: v1
kind: Service
metadata:
  name: quaycr
spec:
  selector:
    app: quaycr
  ports:
  - port: 5000
    name: registry
    targetPort: registry
  - port: 5001
    name: debug
    targetPort: debug
