apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frpc.fullname" . }}
  labels:
    {{- include "frpc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frpc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "frpc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "frpc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              {{.Values.entrypoint | nindent 14}}

          {{with .Values.envSecretName}}
          envFrom:
          - secretRef:
              name: {{.}}
          {{end}}
          {{with .Values.envs}}
          env:
          {{- toYaml . | nindent 12 }}
          {{end}}
          volumeMounts:
          - mountPath: /etc/frp
            name: frp-conf
          ports:
          {{- range $k,$v := .Values.ports}}
          - name: {{$k}}
            containerPort: {{$v.port}}
            protocol: {{$v.protocol | default "TCP"}}
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: frp-conf
        secret:
          {{- if .Values.configSecretName}}
          secretName: {{.Values.configSecretName }}
          {{- else}}
          secretName: {{ include "frpc.fullname" . }}-config
          {{- end}}
