apiVersion: v1
kind: Service
metadata:
  name: {{ include "frpc.fullname" . }}
  labels:
    {{- include "frpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $k,$v := .Values.ports}}
  - name: {{$k}}
    targetPort: {{$k}}
    port: {{$v.servicePort | default $v.port}}
    protocol: {{$v.protocol | default "TCP"}}
  {{- end}}
  selector:
    {{- include "frpc.selectorLabels" . | nindent 4 }}
