apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
  labels:
    app: dind
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: dind
      labels:
        app: dind
    spec:
      enableServiceLinks: false
      hostAliases:
      - hostnames:
        - registry.npmjs.org
        - registry-1.docker.io
        - quay.io
        - proxy.golang.org
        ip: 10.43.0.108 # sni-proxy service ip
      # faster image push
      #- hostnames:
      #  - cr.example.com
      #  ip: 10.10.1.1
      initContainers:
      - name: init
        image: wener/base
        command:
        - sh
        - -c
        - |
          set -ex
          rm /var/run/docker.pid || echo "no pid"
        volumeMounts:
        - mountPath: /var/run
          name: run
      containers:
      - name: dind
        image: docker:24.0.7-dind-alpine3.18
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        args:
        - --insecure-registry=docker-registry:5000
        - --registry-mirror=http://docker-registry:5000
        - --registry-mirror=https://docker.m.daocloud.io
        - --registry-mirror=https://dockercr.wener.me
        - --registry-mirror=https://registry-1.docker.io
        # lower mtu to avoid network problem
        - --mtu=1400
        - --experimental
        - --group=1000
        #- --tls=false
        #- --tlsverify=false
        ports:
        - containerPort: 2375
          name: docker
        - containerPort: 2376
          name: dockers
        startupProbe:
          exec:
            command:
            - docker
            - info
          initialDelaySeconds: 30
        env:
        # 设置为 空 则为 non tls
        - name: DOCKER_TLS_CERTDIR
          value: '/var/lib/docker/certs'
          #value: ''
        volumeMounts:
        - mountPath: /var/lib/docker
          name: data
        - mountPath: /var/run
          name: run
        - mountPath: /cache
          name: cache
      volumes:
      - name: data
        hostPath:
          path: /data/ns/dev-system/dind/data
      - name: run
        hostPath:
          path: /data/ns/dev-system/dind/run
      - name: cache
        hostPath:
          path: /data/ns/dev-system/dind/cache
      restartPolicy: Always
  selector:
    matchLabels:
      app: dind
