apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
  labels:
    app: dind
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: dind
      labels:
        app: dind
    spec:
      containers:
      - name: dind
        image: docker:23.0.1-dind-alpine3.17
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        args:
        - --insecure-registry=docker-registry:5000
        - --registry-mirror=http://docker-registry:5000
        - --registry-mirror=https://registry-1.docker.io
        # lower mtu to avoid network problem
        - --mtu=1400
        - --experimental
        #- --tls=false
        #- --tlsverify=false
        ports:
        - containerPort: 2375
          name: docker
        - containerPort: 2376
          name: dockers
        startupProbe:
          exec:
            command:
            - docker
            - info
        env:
        # 设置为 空 则为 non tls
        - name: DOCKER_TLS_CERTDIR
          value: '/var/lib/docker/certs'
          #value: ''
        volumeMounts:
        - mountPath: /var/lib/docker
          name: data
        - mountPath: /var/run/
          name: run
        - mountPath: /cache
          name: cache
      volumes:
      - name: data
        hostPath:
          path: /data/ns/dev-system/dind/data
      - name: run
        hostPath:
          path: /data/ns/dev-system/dind/run
      - name: cache
        hostPath:
          path: /data/ns/dev-system/dind/cache
      restartPolicy: Always
  selector:
    matchLabels:
      app: dind
