apiVersion: v1
kind: Pod
metadata:
  name: docker-cli
  labels:
    app: docker-cli
spec:
  containers:
  - name: docker
    image: wener/docker
    imagePullPolicy: IfNotPresent
    command:
    - tail
    - -f
    - /dev/null
    env:
    # 用 sock 避免 context create 失败 https://github.com/docker/buildx/issues/413
    # 但 sock 重启失效
    # non-tls
    #- name: DOCKER_HOST
    #  value: tcp://docker:2375
    #- name: DOCKER_TLS_CERTDIR
    #  value: ''
    # tls
    - name: DOCKER_HOST
      value: tcp://docker:2376
    - name: DOCKER_CERT_PATH
      value: '/var/lib/docker/certs/client'
    - name: DOCKER_TLS_VERIFY
      value: '1'
    - name: DOCKER_DRIVER
      value: overlay2
    volumeMounts:
    - mountPath: /var/lib/docker/certs/client
      name: docker-certs
    #- mountPath: /var/run/docker.sock
    #  name: docker-sock
  volumes:
  - name: docker-certs
    hostPath:
      path: /data/ns/dev-system/dind/data/certs/client
  #- name: docker-sock
  #  hostPath:
  #    path: /data/ns/dev-system/dind/run/docker.sock
  #    type: Socket
  restartPolicy: Always

# Test
# docker pull wener/base
# docker tag wener/base docker-registry:5000/wener_base
# 开启了 remoteurl 会失败
# docker push docker-registry:5000/wener_base
# Test Buildx
# docker context create tls
# docker buildx create --name builder --driver docker-container --use tls
# echo FROM wener/base > Dockerfile
# docker buildx build --platform amd64,arm64 .
