apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: [ ]
patches:
- target:
    kind: Application
  path: ./patches/cluster-issuer-acme-email.yaml
- target:
    kind: Issuer
  path: ./patches/issuer-acme-email.yaml
- target:
    kind: ClusterIssuer
  path: ./patches/cluster-issuer-acme-email.yaml
