apiVersion: apps/v1
kind: Deployment
metadata:
  name: frpc-bind
  labels:
    app: frpc-bind
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  template:
    metadata:
      name: frpc-bind
      labels:
        app: frpc-bind
    spec:
      containers:
      - name: frpc-bind
        image: wener/frpc:0.51.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 7400
          name: dashboard
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        envFrom:
        - secretRef:
            # frpc_name, frpc_sk, frps_server_addr, frps_token
            name: frpc-bind-env
        volumeMounts:
        - mountPath: /etc/frp/frpc.ini
          name: conf
          subPath: frpc.ini
      volumes:
      - name: conf
        configMap:
          name: frpc-bind-conf
      restartPolicy: Always
  selector:
    matchLabels:
      app: frpc-bind
---

apiVersion: v1
kind: Service
metadata:
  name: frpc-bind
  labels:
    app: frpc-bind
spec:
  selector:
    app: frpc-bind
  ports:
  - port: 22
    name: ssh
    targetPort: ssh
  - port: 80
    name: http
    targetPort: http
  - port: 443
    name: https
    targetPort: https
  - port: 7400
    name: dashboard
    targetPort: dashboard

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc-bind-conf
  labels:
    app: frpc-bind
data:
  frpc.toml: |
    token = "{{.Envs.frps_token}}"
    # frps
    serverAddr = "{{.Envs.frps_server_addr}}"
    serverPort = 443
    protocol = "wss"
    # for local frps in same cluster
    # serverAddr = "frps"
    # serverPort = 80
    # protocol = "tcp"

    webServer.addr = "0.0.0.0"
    webServer.port = 7400
    webServer.user = "admin"
    webServer.password = "admin"

    transport.useEncryption = true
    transport.useCompression = true

    [[visitors]]
    name = "{{.Envs.frpc_name}}.ssh"
    role = "visitor"
    type = "stcp"
    secretKey = "{{.Envs.frpc_sk}}"
    serverName = "{{.Envs.frpc_name}}.ssh"
    bindAddr = "0.0.0.0"
    bindPort = 22

    [[visitors]]
    name = "{{.Envs.frpc_name}}.http"
    role = "visitor"
    type = "stcp"
    secretKey = "{{.Envs.frpc_sk}}"
    serverName = "{{.Envs.frpc_name}}.http"
    bindAddr = "0.0.0.0"
    bindPort = 80

    [[visitors]]
    name = "{{.Envs.frpc_name}}.https"
    role = "visitor"
    type = "stcp"
    secretKey = "{{.Envs.frpc_sk}}"
    serverName = "{{.Envs.frpc_name}}.https"
    bindAddr = "0.0.0.0"
    bindPort = 443

    [[visitors]]
    name = "{{.Envs.frpc_name}}.prometheus"
    role = "visitor"
    type = "stcp"
    secretKey = "{{.Envs.frpc_sk}}"
    serverName = "{{.Envs.frpc_name}}.prometheus"
    bindAddr = "0.0.0.0"
    bindPort = 19090
