apiVersion: apps/v1
kind: Deployment
metadata:
  name: frps
  labels:
    app: frps
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  template:
    metadata:
      name: frps
      labels:
        app: frps
    spec:
      containers:
      - name: frps
        image: wener/frps:0.53.2
        imagePullPolicy: IfNotPresent
        command:
        - frps
        - -c
        - /etc/frp/frps.toml
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 7500
          name: dashboard
        envFrom:
        - secretRef:
            name: frps-env
        volumeMounts:
        - mountPath: /etc/frp/
          name: conf
      volumes:
      - name: conf
        configMap:
          name: frps-conf
      restartPolicy: Always
  selector:
    matchLabels:
      app: frps

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: frps-conf
data:
  frps.toml: |
    bindAddr = "0.0.0.0"
    bindPort = 80
    quicBindPort = 7001
    kcpBindPort = 80
    vhostHTTPPort = 80
    vhostHTTPSPort = 443
    webServer.addr = "0.0.0.0"
    webServer.port = 7500
    webServer.user = "admin"
    webServer.password = "{{.Envs.frps_dashboard_pwd}}"
    enablePrometheus = true
    token = "{{.Envs.frps_token}}"
    subdomainHost = "{{.Envs.frps_subdomain_host}}"

---

apiVersion: v1
kind: Service
metadata:
  name: frps
spec:
  selector:
    app: frps
  ports:
  - port: 80
    name: http
    targetPort: http
  - port: 443
    name: https
    targetPort: https
  - port: 7500
    name: dashboard
    targetPort: dashboard
