apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-agent
  labels:
    app: vector-agent
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: vector-agent
  template:
    metadata:
      annotations: { }
      labels:
        app: vector-agent
        vector.dev/exclude: "true"
    spec:
      serviceAccountName: vector-agent
      dnsPolicy: ClusterFirst
      containers:
      - name: vector
        image: "timberio/vector:0.29.1-alpine"
        imagePullPolicy: IfNotPresent
        args:
        - --config-dir
        - /etc/vector/
        env:
        - name: VECTOR_SELF_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: VECTOR_SELF_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VECTOR_SELF_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCFS_ROOT
          value: "/host/proc"
        - name: SYSFS_ROOT
          value: "/host/sys"
        envFrom:
        - secretRef:
            name: vector-agent-env
        ports:
        - name: prom-exporter
          containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: "/vector-data-dir"
        - name: config
          mountPath: "/etc/vector/"
          readOnly: true
        - name: var-log
          mountPath: "/var/log/"
          readOnly: true
        - name: var-lib
          mountPath: "/var/lib"
          readOnly: true
        - name: procfs
          mountPath: "/host/proc"
          readOnly: true
        - name: sysfs
          mountPath: "/host/sys"
          readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              name: vector-agent
      - name: data
        hostPath:
          path: "/var/lib/vector"
      - name: var-log
        hostPath:
          path: "/var/log/"
      - name: var-lib
        hostPath:
          path: "/var/lib/"
      - name: procfs
        hostPath:
          path: "/proc"
      - name: sysfs
        hostPath:
          path: "/sys"
