apiVersion: v1
kind: Service
metadata:
  name: vector-agent-headless
  labels:
    app: vector-agent
  annotations: { }
spec:
  clusterIP: None
  ports:
  - name: datadog-agent
    port: 8282
    protocol: TCP
  - name: fluent
    port: 24224
    protocol: TCP
  - name: logstash
    port: 5044
    protocol: TCP
  - name: splunk-hec
    port: 8080
    protocol: TCP
  - name: statsd
    port: 8125
    protocol: TCP
  - name: syslog
    port: 9000
    protocol: TCP
  - name: vector
    port: 6000
    protocol: TCP
  - name: prom-exporter
    port: 9090
    protocol: TCP
  selector:
    app: vector-agent
  type: ClusterIP
