apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  labels:
    app: keycloak
stringData:
  admin_password: ""
  postgres_db: "keycloak"
  postgres_user: "keycloak"
  postgres_password: ""
