keycloak:
  auth:
    adminUser: keycloak
    existingSecret: keycloak-secret
    passwordSecretKey: admin_password
  externalDatabase:
    host: postgres.data-system
    existingSecret: keycloak-secret
    existingSecretDatabaseKey: postgres_db
    existingSecretUserKey: postgres_user
    existingSecretPasswordKey: postgres_password
  production: true
  proxy: edge
  podAnnotations:
    reloader.stakater.com/auto: 'true'
  metrics:
    enabled: true
  postgresql:
    enabled: false
