apiVersion: v1
kind: Secret
metadata:
  name: supabase-studio-env
  labels:
    app: supabase
    component: studio
stringData:
  DEFAULT_ORGANIZATION_NAME: Default Organization
  DEFAULT_PROJECT_NAME: Default Project

  SUPABASE_ANON_KEY: $(ANON_KEY)
  SUPABASE_SERVICE_KEY: $(SERVICE_KEY)

  SUPABASE_URL: http://supabase-kong:8000
  SUPABASE_PUBLIC_URL: http://supabase.example.com

  STUDIO_PG_META_URL: http://supabase-meta:8080
  POSTGRES_PASSWORD: $(SERVICE_KEY)
