apiVersion: v1
kind: Secret
metadata:
  name: supabase-storage-env
  labels:
    app: supabase
    component: storage
stringData:
  ANON_KEY: $(ANON_KEY)
  SERVICE_KEY: $(SERVICE_KEY)
  PGRST_JWT_SECRET: $(JWT_SECRET)
  POSTGREST_URL: http://supabase-rest:3000
  DATABASE_URL: postgres://supabase_storage_admin:$(DB_PASSWORD)@supabase-db:5432/postgres
