apiVersion: v1
kind: Secret
metadata:
  name: supabase-auth-env
  labels:
    app: supabase
    component: auth
stringData:
  GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:$(DB_PASSWORD)@supabase-db:5432/postgres
  GOTRUE_JWT_SECRET: $(JWT_SECRET)
  API_EXTERNAL_URL: http://supabase.example.com
  GOTRUE_SITE_URL: http://studio.supabase.example.com

  GOTRUE_API_HOST: 0.0.0.0
  GOTRUE_API_PORT: '9999'


  GOTRUE_DB_DRIVER: postgres

  GOTRUE_URI_ALLOW_LIST: ''
  GOTRUE_DISABLE_SIGNUP: 'true'

  GOTRUE_JWT_ADMIN_ROLES: service_role
  GOTRUE_JWT_AUD: authenticated
  GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
  GOTRUE_JWT_EXP: '3600'

  GOTRUE_EXTERNAL_EMAIL_ENABLED: 'false'
  GOTRUE_MAILER_AUTOCONFIRM: 'false'
  # GOTRUE_MAILER_SECURE_EMAIL_CHANGE_ENABLED: true
  # GOTRUE_SMTP_MAX_FREQUENCY: 1s
  GOTRUE_SMTP_ADMIN_EMAIL: admin@example.com
  GOTRUE_SMTP_HOST: supabase-mail
  GOTRUE_SMTP_PORT: '2500'
  GOTRUE_SMTP_USER: fake_mail_user
  GOTRUE_SMTP_PASS: fake_mail_password
  GOTRUE_SMTP_SENDER_NAME: fake_sender
  GOTRUE_MAILER_URLPATHS_INVITE: /auth/v1/verify
  GOTRUE_MAILER_URLPATHS_CONFIRMATION: /auth/v1/verify
  GOTRUE_MAILER_URLPATHS_RECOVERY: /auth/v1/verify
  GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: /auth/v1/verify

  GOTRUE_EXTERNAL_PHONE_ENABLED: 'false'
  GOTRUE_SMS_AUTOCONFIRM: 'true'
  MFA_ENABLED: 'false'
