apiVersion: v1
kind: Secret
metadata:
  name: supabase-rest-env
stringData:
  PGRST_DB_URI: postgres://authenticator:$(DB_PASSWORD)@supabase-db:5432/postgres
  PGRST_DB_SCHEMAS: public,storage,graphql_public
  PGRST_DB_ANON_ROLE: anon
  PGRST_JWT_SECRET: $(JWT_SECRET)
  PGRST_DB_USE_LEGACY_GUCS: "false"
