apiVersion: v1
kind: Secret
metadata:
  name: supabase-realtime-env
  labels:
    app: supabase
    component: realtime
stringData:
  PORT: '4000'
  DB_HOST: supabase-db
  DB_PORT: '5432'
  DB_USER: supabase_admin
  DB_PASSWORD: $(DB_PASSWORD)
  DB_NAME: postgres
  DB_AFTER_CONNECT_QUERY: 'SET search_path TO _realtime'
  # cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | head -c 16
  DB_ENC_KEY: $(DB_ENC_KEY)
  API_JWT_SECRET: $(JWT_SECRET)
  #FLY_ALLOC_ID: fly123
  #FLY_APP_NAME: realtime
  # cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | head -c 64
  SECRET_KEY_BASE: $(SECRET_KEY_BASE)
  ERL_AFLAGS: -proto_dist inet_tcp
  ENABLE_TAILSCALE: "false"
  DNS_NODES: "''"
