apiVersion: v1
kind: Secret
metadata:
  name: supabase-meta-env
  labels:
    app: supabase
    component: meta
stringData:
  PG_META_PORT: '8080'
  PG_META_DB_HOST: supabase-db
  PG_META_DB_PORT: '5432'
  PG_META_DB_NAME: postgres
  PG_META_DB_USER: supabase_admin
  PG_META_DB_PASSWORD: $(DB_PASSWORD)
