apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./controller.yaml

images:
- name: quay.io/bitnami/sealed-secrets-controller
  newName: registry.cn-hongkong.aliyuncs.com/cmi/bitnami_sealed-secrets-controller

patches:
- target:
    kind: Deployment
    name: sealed-secrets-controller
  path: sealed-secrets-controller.deploy.patch.yaml
