apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
spec:
  template:
    spec:
      containers:
      - name: sealed-secrets-controller
        # https://github.com/bitnami-labs/sealed-secrets/blob/main/RELEASE-NOTES.md#v0150
        env:
        - name: SEALED_SECRETS_UPDATE_STATUS
          value: '1'


