apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-system
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: storage-system
  source:
    path: storage-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
