apiVersion: v1
kind: Secret
metadata:
  name: appwrite-mariadb-env
  labels:
    app: appwrite
    component: mariadb
stringData:
  MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
  MYSQL_PASSWORD: $(MYSQL_PASSWORD)
  MYSQL_DATABASE: appwrite
  MYSQL_USER: appwrite
