apiVersion: v1
kind: Service
metadata:
  name: zincobserve
  labels:
    app: zincobserve
spec:
  clusterIP: None
  selector:
    app: zincobserve
  ports:
  - name: http
    port: 5080
    targetPort: 5080

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zincobserve
  labels:
    app: zincobserve
spec:
  serviceName: zincobserve
  replicas: 1
  selector:
    matchLabels:
      app: zincobserve
  template:
    metadata:
      labels:
        app: zincobserve
    spec:
      # terminationGracePeriodSeconds: 0
      initContainers:
      - name: take-data-dir-ownership
        image: quay.io/wener/base
        command:
        - chown
        - -R
        - 10000:3000
        - /data
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - name: zincobserve
        image: public.ecr.aws/zinclabs/zincobserve:latest
        securityContext:
          #fsGroup: 2000
          runAsUser: 10000
          runAsGroup: 3000
          runAsNonRoot: true
        env:
        - name: ZO_DATA_DIR
          value: /data
        - name: ZO_TELEMETRY
          value: 'false'
        envFrom:
        - secretRef:
            name: zincobserve-env
        # command: ["/bin/bash", "-c", "while true; do sleep 1; done"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 4096m
            memory: 8Gi
          requests:
            cpu: 256m
            memory: 50Mi
        ports:
        - containerPort: 5080
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        hostPath:
          path: /data/ns/monitoring-system/zincobserve/data
