apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # 按需
    namespace: auth
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: oauth2-proxy
    repoURL: 'git@gitea-ssh.gitea:dev/dev-cluster'
    targetRevision: HEAD
    helm:
      releaseName: oauth2-proxy
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
