apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "samba.fullname" . }}-conf
  labels:
    {{- include "samba.labels" . | nindent 4 }}
data:
  {{- with .Values.config.smb}}
  smb.ini: |
    {{. | nindent 4}}
  {{- end}}
