apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: monitoring/services/kube-prometheus
    repoURL: https://code.wener.me/wenerme/kube-stub-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      #selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
