apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        # https://hub.docker.com/r/supabase/postgres
        image: supabase/postgres:15.1.0.64
        #image: postgres:15.2-alpine
        imagePullPolicy: IfNotPresent
        # https://pgtune.leopard.in.ua/
        # WebApp 8C32G 1000 Conn
        args:
        - -cmax_connections=1000
        - -cshared_buffers=8GB
        - -ceffective_cache_size=24GB
        - -cmaintenance_work_mem=2GB
        - -ccheckpoint_completion_target=0.9
        - -cwal_buffers=16MB
        - -cdefault_statistics_target=100
        - -crandom_page_cost=4
        - -ceffective_io_concurrency=2
        - -cwork_mem=2097kB
        - -cmin_wal_size=1GB
        - -cmax_wal_size=4GB
        - -cmax_worker_processes=8
        - -cmax_parallel_workers_per_gather=4
        - -cmax_parallel_workers=8
        - -cmax_parallel_maintenance_workers=4
        - -cshared_preload_libraries=pg_stat_statements,pg_stat_monitor,pgaudit,plpgsql,plpgsql_check,pg_cron,pg_net,pgsodium,timescaledb,auto_explain,pg_tle
        ports:
        - containerPort: 5432
          name: postgres
          hostPort: 5432
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        # default en.UTF-8, collate is better for common usage
        - name: POSTGRES_INITDB_ARGS
          value: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
        - name: POSTGRES_PASSWORD
          value: $(POSTGRES_PASSWORD)
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/pgdata
          name: data
      volumes:
      - name: data
        hostPath:
          path: /data/ns/data-system/postgres/data

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    name: postgres
    targetPort: postgres
