apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
  - port: 5432
    name: postgres
    targetPort: postgres
    nodePort: 30002
