gitlab-runner:
  runners:
    name: k8s-runner
    tags: "kubernetes"
    runUntagged: true
    protected: false
    # secret for runner-registration-token, runner-token
    secret: gitlab-runner
    config: |
      [[runners]]
        [runners.kubernetes]
          namespace = "{{.Release.Namespace}}"
          image = "wener/base"

  gitlabUrl: https://gitlab.com/
  # inline token - prefer runners.secret
  #runnerToken: ""
  #runnerRegistrationToken: ""

  concurrent: 10
  checkInterval: 30

  # Unregister all runners before termination
  unregisterRunners: true
  terminationGracePeriodSeconds: 3600
