apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "*"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/wenerme/kube-stub-cluster.git'
    targetRevision: HEAD
