postgres-operator:
  image:
    registry: registry.cn-hongkong.aliyuncs.com
    repository: cmi/acid_postgres-operator
  # 自定义了 image 相关配置 - 其他配置与默认相同 - 因为使用了 CRD 要求类型正确，因此需要写
  configTarget: "OperatorConfigurationCRD"
  configGeneral:
    docker_image: registry.cn-hongkong.aliyuncs.com/cmi/acid_spilo-13:2.0-p4
    enable_crd_validation: true
    enable_lazy_spilo_upgrade: false
    enable_pgversion_env_var: true
    enable_shm_volume: true
    enable_spilo_wal_path_compat: false
    etcd_host: ""
    min_instances: -1
    max_instances: -1
    repair_period: 5m
    resync_period: 30m
    workers: 8

  configConnectionPooler:
    connection_pooler_image: registry.cn-hongkong.aliyuncs.com/cmi/acid_pgbouncer:master-14
    connection_pooler_max_db_connections: 60
    connection_pooler_number_of_instances: 2

  configTeamsApi:
    enable_postgres_team_crd: true
    enable_team_superuser: false
    enable_teams_api: false
    pam_role_name: zalandos
    protected_role_names:
    - admin
    team_admin_role: admin
    team_api_role_configuration:
      log_statement: all
  crd:
    # HELM 3 不需要
    create: false
  configKubernetes:
    enable_init_containers: true
    enable_pod_antiaffinity: false
    enable_pod_disruption_budget: true
    enable_sidecars: true
    spilo_privileged: false
    cluster_labels:
      application: spilo
    # 使用 secret
    # https://github.com/zalando/postgres-operator/issues/1348
    pod_environment_configmap: postgres-operator/postgres-operator-env
    # v1.6.1 FIX
    # https://github.com/zalando/postgres-operator/issues/1377
    additional_pod_capabilities:
    - SYS_NICE
  configDebug:
    debug_logging: true
    enable_database_access: true
  configLoggingRestApi:
    api_port: 8080
    cluster_history_entries: 1000
    ring_log_lines: 500
  configAwsOrGcp:
    enable_ebs_gp3_migration: false
    log_s3_bucket: "example-log"
    wal_s3_bucket: "example-backup"
  configLogicalBackup:
    logical_backup_docker_image: registry.cn-hongkong.aliyuncs.com/cmi/acid_logical-backup:v1.6.1
    logical_backup_s3_bucket: "example-backup"
    logical_backup_s3_endpoint: "https://oss.example.com"
    logical_backup_s3_region: ""
    logical_backup_s3_access_key_id: ""
    logical_backup_s3_secret_access_key: ""
    logical_backup_s3_sse: ""

  configLoadBalancer:
    enable_master_load_balancer: false
    enable_replica_load_balancer: false
