apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  namespace: argocd
  labels:
    syncer/dev-example-com-cert: 'true'

---

apiVersion: v1
kind: Namespace
metadata:
  name: dev-system
  namespace: dev-system
  labels:
    syncer/dev-example-com-cert: 'true'

---

apiVersion: v1
kind: Namespace
metadata:
  name: data-system
  namespace: data-system

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-system
  namespace: monitoring-system

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  namespace: monitoring
