apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-ops
  namespace: argocd
stringData:
  type: git
  url: git@github.com:wenerme/kube-stub-cluster.git
  name: ops
  sshPrivateKey: |
  # do not check ssh host key
  insecure: 'true'
  #username: ''
  #password: ''
