apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kustomize edit add resource templates/*.yaml
resources:
- install.yaml

images:
- name: ghcr.io/dexidp/dex
  newName: registry.cn-hongkong.aliyuncs.com/cmi/dexidp_dex
- name: argoproj/argocd
  newName: registry.cn-hongkong.aliyuncs.com/cmi/argoproj_argocd
- name: quay.io/argoproj/argocd
  newName: registry.cn-hongkong.aliyuncs.com/cmi/argoproj_argocd

patches:
- target:
    name: argocd-cm
  path: patches/argocd-cm.yaml
# unify cluster, project and repo
#- target:
#    kind: Application
#  path: patches/app-proj-repo.yaml
