
forward:
	kubectl port-forward svc/argocd-server -n argocd 8443:443
passwd:
	which pbcopy && kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o name | cut -d'/' -f 2 | pbcopy

wait:
  kubectl get --namespace argocd deployments.apps argocd-server -w

watch:
  kubectl get events --namespace argocd -w
