REPO_ROOT ?= $(shell git rev-parse --show-toplevel)
-include $(REPO_ROOT)/k8s.mk

info:
build:
seal:

up:
up-verify: up verify
up-verify-server: up verify-server
up-build: up build

apply:
ns:
delete:
images:
