apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-kube-stub-cluster
  namespace: argocd
stringData:
  type: git
  url: https://github.com/wenerme/kube-stub-cluster.git
  name: kube-stub-cluster
  username: ''
  password: ''
