apiVersion: v1
kind: Secret
metadata:
  name: nacos-env
  labels:
    app: nacos
stringData:
  NACOS_AUTH_ENABLE: 'true'
  # random-string | base64 | pbcopy
  NACOS_AUTH_TOKEN: $(NACOS_AUTH_TOKEN)
  MYSQL_SERVICE_PASSWORD: $(MYSQL_SERVICE_PASSWORD)
  NACOS_AUTH_CACHE_ENABLE: 'true'
  SPRING_DATASOURCE_PLATFORM: mysql
  MYSQL_SERVICE_HOST: mysql
  MYSQL_SERVICE_PORT: '3306'
  MYSQL_SERVICE_DB_NAME: nacos
  MYSQL_SERVICE_USER: nacos
