apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: take-data-dir-ownership
        image: alpine
        command:
        - chown
        - -R
        - 1000:1000
        - /data
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - name: mysql
        # -debian 无 arm
        image: mysql:8.0.32
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sh", "-c", "mysqladmin -u root shutdown" ]
        args:
        # basic
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --max-connections=2000
        # case by case
        #- --log_bin_trust_function_creators=1
        # Logging
        - --log-output=FILE,TABLE
        - --slow-query-log=1
        - --slow-query-log-file=/var/lib/mysql/slow.log # HOSTNAME-slow.log
        - --long-query-time=5
        - --log-queries-not-using-indexes
        # IO+Memory
        # - --innodb_io_capacity=2000 # for SSD
        # - --innodb_thread_concurrency=0
        # - --innodb_read_io_threads=64 # default=4
        # - --innodb_write_io_threads=64
        # - --innodb_buffer_pool_size=64G
        # ZFS Tuning
        # - --sync_binlog=0
        # - --innodb_flush_log_at_trx_commit=0
        # - --innodb_flush_method=fsync
        # - --innodb_doublewrite=0
        # - --innodb_use_native_aio=0
        # - --innodb_checksum_algorithm=none
        # - --innodb_log_write_ahead_size=16384   #=16k
        # - --innodb_flush_neighbors=0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: MYSQL_ROOT_HOST
          value: '%'
        - name: MYSQL_ROOT_PASSWORD
          value: $(MYSQL_ROOT_PASSWORD)

        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      volumes:
      - name: data
        hostPath:
          path: /data/ns/data-system/mysql/data

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    name: mysql
    targetPort: mysql

