apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
  - port: 3306
    name: mysql
    targetPort: mysql
    nodePort: 30001
