apiVersion: v1
kind: Secret
metadata:
  name: acme-dns
  namespace: cluster-manifest
stringData:
  # curl -sX POST https://auth.acme-dns.io/register | jq
  # CNAME _acme-challenge.dev.example.com -CNAME-> fulldomain
  acme-dns.json: |
    {
      "dev.example.com": {
        "username": "",
        "password": "",
        "fulldomain": "",
        "subdomain": "",
        "allowfrom": []
      }
    }

