apiVersion: v1
kind: Service
metadata:
  name: openobserve
  labels:
    app: openobserve
spec:
  clusterIP: None
  selector:
    app: openobserve
  ports:
  - name: http
    port: 5080
    targetPort: 5080
  - name: http
    port: 5080
    targetPort: 80

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openobserve
  labels:
    app: openobserve
spec:
  serviceName: openobserve
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
  template:
    metadata:
      labels:
        app: openobserve
    spec:
      # terminationGracePeriodSeconds: 0
      initContainers:
      - name: take-data-dir-ownership
        image: quay.io/wener/base
        command:
        - chown
        - -R
        - 10000:3000
        - /data
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - name: openobserve
        image: openobserve/openobserve:v0.4.8
        imagePullPolicy: IfNotPresent
        securityContext:
          #fsGroup: 2000
          runAsUser: 10000
          runAsGroup: 3000
          runAsNonRoot: true
        startupProbe:
          httpGet:
            port: http
            path: /healthz
        env:
        - name: ZO_DATA_DIR
          value: /data
        - name: ZO_TELEMETRY
          value: 'false'
        - name: ZO_COMPACT_DATA_RETENTION_DAYS
          value: '30'
        envFrom:
        - secretRef:
            name: openobserve-env
        resources:
          limits:
            cpu: 8000m
            memory: 32Gi
          requests:
            cpu: 256m
            memory: 50Mi
        ports:
        - containerPort: 5080
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        hostPath:
          path: /data/ns/data-system/openobserve/data

