metallb:
  speaker:
    # prevent evict
    priorityClassName: system-node-critical
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  configInline:
    address-pools:
    - name: default
      protocol: layer2
      # default address space
      addresses:
      - 10.10.128.0/18
