apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml

images:
- name: quay.io/argocdapplicationset/argocd-applicationset
  newName: registry.cn-hongkong.aliyuncs.com/cmi/argocdapplicationset_argocd-applicationset
