ingress-nginx:
  config:
    hide-headers: "Server"
  controller:
    image:
      # use mirror
      # k8s.gcr.io/ingress-nginx/controller
      repository: registry.cn-hongkong.aliyuncs.com/cmi/ingress-nginx_controller
      # disable digest
      digest: ""
    kind: DaemonSet
    hostPort:
      enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: false
    admissionWebhooks:
      patch:
        image:
          repository: registry.cn-hongkong.aliyuncs.com/cmi/ingress-nginx_kube-webhook-certgen
          digest: ""
    extraArgs:
      # Allowed SNI routing - affect performance
      enable-ssl-passthrough: true
    # default ingress class
    watchIngressWithoutClass: true
    ingressClassResource:
      default: true
