apiVersion: v1
kind: Service
metadata:
  name: sni-proxy
spec:
  selector:
    app: gost
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
    name: http
  - protocol: TCP
    port: 443
    targetPort: https
    name: https
  clusterIP: 10.43.0.108
