apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - name: redis
    targetPort: redis
    nodePort: 30637
    port: 6379
