apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app: redis
stringData:
  # Redis 6+ ACL username and password
  # nopass -> #SHA256
  users.acl: |
    user default nopass on ~* &* +@all

# user default off
# uuidgen | tee /dev/fd/2 | tr -d '[:space:]' | sha256sum
