apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0.12-alpine
        imagePullPolicy: IfNotPresent
        command:
        - redis-server
        - /etc/redis/redis.conf
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: conf
          mountPath: /etc/redis
        - name: secret
          mountPath: /secret
        - name: data
          mountPath: /data
      volumes:
      - name: conf
        configMap:
          name: redis-conf
      - name: secret
        secret:
          secretName: redis-secret
      - name: data
        hostPath:
          path: /data/ns/data-system/redis/data
      restartPolicy: Always
  selector:
    matchLabels:
      app: redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    name: redis
    targetPort: redis

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
  labels:
    app: redis
data:
  redis.conf: |
    dir /data
    appendonly yes
    save 60 1000
    aclfile /secret/users.acl
