apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - type: git
      url: https://github.com/wenerme/kube-stub-cluster
      usernameSecret:
        key: username
        name: repo-stub-cluster
      passwordSecret:
        key: password
        name: repo-stub-cluster
